<?php

return array(
	'version' => '0.9.4.1',
	'pgcache.enabled' => true,
	'pgcache.engine' => 'file_generic',
	'minify.enabled' => false,
	'minify.auto' => true,
	'minify.engine' => 'file',
	'minify.html.engine' => 'html',
	'minify.js.engine' => 'js',
	'minify.css.engine' => 'css',
	'dbcache.enabled' => true,
	'dbcache.engine' => 'file',
	'objectcache.enabled' => false,
	'objectcache.engine' => 'file',
	'browsercache.enabled' => true,
	'cdn.enabled' => false,
	'cdn.engine' => 'mirror',
	'varnish.enabled' => false,
	'varnish.servers' => array(
		0 => '',
	),
	'newrelic.enabled' => false,
	'newrelic.api_key' => '',
	'newrelic.account_id' => '',
	'newrelic.appname' => '',
	'newrelic.application_id' => 0,
	'plugin.license_key' => '',
	'widget.pagespeed.enabled' => true,
	'widget.pagespeed.key' => '',
	'config.check' => true,
	'pgcache.file.nfs' => false,
	'minify.file.nfs' => false,
	'dbcache.file.locking' => false,
	'objectcache.file.locking' => false,
	'pgcache.file.locking' => false,
	'minify.file.locking' => false,
	'common.instance_id' => 1738665719,
	'plugin.type' => '',
	'cdn.uploads.enable' => true,
	'cdn.includes.enable' => true,
	'cdn.theme.enable' => true,
	'cdn.custom.enable' => true,
	'cdn.import.external' => false,
	'cdn.canonical_header' => false,
	'cdn.mirror.ssl' => 'auto',
	'cdn.reject.ssl' => false,
	'cdn.reject.logged_roles' => false,
	'cdn.reject.roles' => array(
		0 => '',
	),
	'cdn.includes.files' => '*.css;*.js;*.gif;*.png;*.jpg;*.xml',
	'cdn.theme.files' => '*.css;*.js;*.gif;*.png;*.jpg;*.ico;*.ttf;*.otf,*.woff,*.less',
	'cdn.import.files' => '',
	'cdn.custom.files' => array(
		0 => 'favicon.ico',
		1 => '{wp_content_dir}/gallery/*',
		2 => '{wp_content_dir}/uploads/avatars/*',
		3 => '{plugins_dir}/wordpress-seo/css/xml-sitemap.xsl',
		4 => '{plugins_dir}/wp-minify/min*',
		5 => '{plugins_dir}/*.js',
		6 => '{plugins_dir}/*.css',
		7 => '{plugins_dir}/*.gif',
		8 => '{plugins_dir}/*.jpg',
		9 => '{plugins_dir}/*.png',
	),
	'cdn.reject.ua' => array(
		0 => '',
	),
	'cdn.reject.files' => array(
		0 => '{uploads_dir}/wpcf7_captcha/*',
		1 => '{uploads_dir}/imagerotator.swf',
		2 => '{plugins_dir}/wp-fb-autoconnect/facebook-platform/channel.html',
	),
	'cdn.mirror.domain' => array(
		0 => 'd200ylkyf3qp40.cloudfront.net',
	),
	'cdn.debug' => false,
	'browsercache.replace.exceptions' => array(
		0 => '',
	),
	'browsercache.no404wp' => false,
	'browsercache.no404wp.exceptions' => array(
		0 => 'robots\\.txt',
		1 => '[a-z0-9_\\-]*sitemap[a-z0-9_\\-]*\\.(xml|xsl|html)(\\.gz)?',
	),
	'browsercache.cssjs.last_modified' => true,
	'browsercache.cssjs.expires' => true,
	'browsercache.cssjs.lifetime' => 31536000,
	'browsercache.cssjs.cache.control' => true,
	'browsercache.cssjs.cache.policy' => 'cache_public_maxage',
	'browsercache.cssjs.etag' => false,
	'browsercache.cssjs.w3tc' => false,
	'browsercache.cssjs.compression' => true,
	'browsercache.cssjs.replace' => false,
	'browsercache.cssjs.nocookies' => true,
	'browsercache.html.last_modified' => true,
	'browsercache.html.expires' => true,
	'browsercache.html.lifetime' => 3600,
	'browsercache.html.cache.control' => true,
	'browsercache.html.cache.policy' => 'cache_public_maxage',
	'browsercache.html.etag' => false,
	'browsercache.html.w3tc' => false,
	'browsercache.html.compression' => true,
	'browsercache.other.last_modified' => true,
	'browsercache.other.expires' => true,
	'browsercache.other.lifetime' => 31536000,
	'browsercache.other.cache.control' => true,
	'browsercache.other.cache.policy' => 'cache_public_maxage',
	'browsercache.other.etag' => false,
	'browsercache.other.w3tc' => false,
	'browsercache.other.compression' => true,
	'browsercache.other.replace' => false,
	'browsercache.other.nocookies' => true,
	'browsercache.timestamp' => '1445170931',
	'notes.need_empty_minify' => true,
	'minify.debug' => false,
	'cdn.minify.enable' => false,
	'dbcache.reject.logged' => true,
	'dbcache.lifetime' => 180,
	'dbcache.file.gc' => 3600,
	'dbcache.reject.uri' => array(
		0 => '',
	),
	'dbcache.reject.sql' => array(
		0 => 'gdsr_',
		1 => 'wp_rg_',
		2 => '_wp_session_',
		3 => '_wc_session_',
	),
	'dbcache.reject.words' => array(
		0 => '^\\s*insert\\b',
		1 => '^\\s*delete\\b',
		2 => '^\\s*update\\b',
		3 => '^\\s*replace\\b',
		4 => '^\\s*create\\b',
		5 => '^\\s*alter\\b',
		6 => '^\\s*show\\b',
		7 => '^\\s*set\\b',
		8 => '\\bautoload\\s+=\\s+\'yes\'',
		9 => '\\bsql_calc_found_rows\\b',
		10 => '\\bfound_rows\\(\\)',
		11 => '\\bw3tc_request_data\\b',
	),
	'dbcache.debug' => false,
	'pgcache.cache.home' => true,
	'pgcache.reject.front_page' => false,
	'pgcache.cache.feed' => false,
	'pgcache.cache.ssl' => false,
	'pgcache.cache.404' => false,
	'pgcache.check.domain' => false,
	'pgcache.reject.logged' => true,
	'pgcache.reject.logged_roles' => false,
	'pgcache.reject.roles' => array(
		0 => '',
	),
	'pgcache.prime.enabled' => true,
	'pgcache.prime.interval' => 900,
	'pgcache.prime.limit' => 10,
	'pgcache.prime.sitemap' => '',
	'pgcache.prime.post.enabled' => false,
	'pgcache.purge.front_page' => false,
	'pgcache.purge.home' => true,
	'pgcache.purge.post' => true,
	'pgcache.purge.feed.blog' => true,
	'pgcache.purge.comments' => true,
	'pgcache.purge.author' => true,
	'pgcache.purge.terms' => true,
	'pgcache.purge.feed.comments' => true,
	'pgcache.purge.feed.author' => true,
	'pgcache.purge.feed.terms' => true,
	'pgcache.purge.archive.daily' => true,
	'pgcache.purge.archive.monthly' => true,
	'pgcache.purge.archive.yearly' => true,
	'pgcache.purge.feed.types' => array(
		0 => 'rdf',
		1 => 'rss',
		2 => 'rss2',
		3 => 'atom',
	),
	'pgcache.purge.postpages_limit' => 10,
	'pgcache.purge.pages' => array(
		0 => '',
	),
	'pgcache.purge.sitemap_regex' => '([a-z0-9_\\-]*?)sitemap([a-z0-9_\\-]*)?\\.xml',
	'pgcache.late_init' => false,
	'pgcache.compatibility' => false,
	'pgcache.remove_charset' => false,
	'pgcache.file.gc' => 3600,
	'pgcache.comment_cookie_ttl' => 1800,
	'pgcache.accept.qs' => array(
		0 => '',
	),
	'pgcache.reject.ua' => array(
		0 => '',
	),
	'pgcache.reject.cookie' => array(
		0 => 'wptouch_switch_toggle',
	),
	'pgcache.reject.uri' => array(
		0 => 'wp-.*\\.php',
		1 => 'index\\.php',
	),
	'pgcache.accept.files' => array(
		0 => 'wp-comments-popup.php',
		1 => 'wp-links-opml.php',
		2 => 'wp-locations.php',
	),
	'pgcache.accept.uri' => array(
		0 => 'sitemap(_index)?\\.xml(\\.gz)?',
		1 => '([a-z0-9_\\-]+)?sitemap\\.xsl',
		2 => '[a-z0-9_\\-]+-sitemap([0-9]+)?\\.xml(\\.gz)?',
	),
	'pgcache.debug' => false,
	'notes.need_empty_pgcache' => true,
	'notes.plugins_updated' => false,
);